services:
  nextjs:
    container_name: journal_nextjs
    image: 'journal/nextjs'
    build:
      context: .
      dockerfile: ./.docker/nextjs/Dockerfile
    restart: unless-stopped
    volumes:
      - journal_uploads:/app/uploads
  nginx:
    container_name: journal_nginx
    image: 'journal/nginx'
    build:
      context: ./.docker/nginx
    depends_on:
      - nextjs
    volumes:
      - journal_uploads:/usr/share/nginx/html/uploads
    ports:
      - 8080:80

volumes:
  journal_uploads:
    external: true
